// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Context;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(DespachoContext))]
    [Migration("20220830180303_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApi.Models.Cerveza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("FabricanteId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FabricanteId");

                    b.ToTable("Cerveza", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Cerveza más elegida desde 1890.",
                            FabricanteId = 1,
                            Nombre = "Classic"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Cerveza Ipa fabricanda en el sur de la Patagonia Argentina.",
                            FabricanteId = 2,
                            Nombre = "IPA"
                        });
                });

            modelBuilder.Entity("WebApi.Models.Fabricante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Fabricante", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Quilmes"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Patagonia"
                        });
                });

            modelBuilder.Entity("WebApi.Models.Cerveza", b =>
                {
                    b.HasOne("WebApi.Models.Fabricante", "Fabricante")
                        .WithMany("Cervezas")
                        .HasForeignKey("FabricanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fabricante");
                });

            modelBuilder.Entity("WebApi.Models.Fabricante", b =>
                {
                    b.Navigation("Cervezas");
                });
#pragma warning restore 612, 618
        }
    }
}
